version: '3.7'

services:
  mysql_8_0:
    container_name: ddev-${DDEV_SITENAME}-mysql_8_0
    image: mysql:8.0
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      MYSQL_ROOT_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10303:3306"
