version: '3.7'

services:
  mysql_5_7:
    container_name: ddev-${DDEV_SITENAME}-mysql_5_7
    image: mysql:5.7
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      MYSQL_ROOT_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10302:3306"
