version: '3.7'

services:
  mysql_5_6:
    container_name: ddev-${DDEV_SITENAME}-mysql_5_6
    image: mysql:5.6
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      MYSQL_ROOT_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10301:3306"
