version: '3.7'

services:
  postgres_9_5:
    container_name: ddev-${DDEV_SITENAME}-postgres_9_5
    image: postgres:9.5
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      POSTGRES_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10401:5432"
