version: '3.7'

services:
  postgres_12:
    container_name: ddev-${DDEV_SITENAME}-postgres_12
    image: postgres:12
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      POSTGRES_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10405:5432"
