version: '3.7'

services:
  postgres_14:
    container_name: ddev-${DDEV_SITENAME}-postgres_14
    image: postgres:14
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      POSTGRES_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10407:5432"
