version: '3.7'

services:
  postgres_15:
    container_name: ddev-${DDEV_SITENAME}-postgres_15
    image: postgres:15
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      POSTGRES_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10408:5432"
