version: '3.7'

services:
  mariadb_10_2:
    container_name: ddev-${DDEV_SITENAME}-mariadb_10_2
    image: mariadb:10.2
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      MYSQL_ROOT_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10101:3306"
