version: '3.7'

services:
  postgres_11:
    container_name: ddev-${DDEV_SITENAME}-postgres_11
    image: postgres:11
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      POSTGRES_PASSWORD: 'pseudify(!)w4ldh4ck3r'
    ports:
      - "10404:5432"
